### PR TITLE
Make timeout for Ajax call configurable

### PR DESCRIPTION
**Pull request by 3link**
Short description if any.

Author Todo List:

- [ ] Add/adjust tests (if applicable)
- [x] Build in CI passes
- [x] Latest master revision is merged into the branch
- [x] Self-Review
- [x] Set `Ready For Review` status

### CODE REVIEW

**Review by wi101 — APPROVED** [review]
it's draft, but LGTM thanks!

**Review by peixunzhang — APPROVED** [review]

**Review by mschuwalow — APPROVED** [review]
Let's document this new option

**Review by SuperIzya — APPROVED** [review]

**Comment by 3link** [comment]
> Let's document this new option

Done in 339265e1a3c6e27759db288d2aea07f78f2b9adf

**Comment by 3link** [comment]
Adjusted the doc further: https://github.com/LiveIntent/live-connect/blob/dfe20880911ad012916c953ece3577c179fc52de/CONFIGURATION_OPTIONS.md

**Comment by robertrmartinez** [comment]
@3link Awesome!

I see 6.0.1 was released.

If I just build prebid locally and bump the live-connect package to this version I should be good right?

I figure you will make a PR to prebid to do this, but wondering if I can do a patch fix on older versions of prebid in my fork and it should work right?

Thanks for the quick fix!

**Comment by robertrmartinez** [comment]
Also just to point out, if one does not use `ajaxTimeout` setting, then it still defaults to `0`

I thought that in this PR you would also have the default updated to something else valid?

Like 3000 or something.

**Comment by robertrmartinez** [comment]
Even when using the pbjs liveintent config param ajaxTimeout I get it set to 0

I probably am doing somethign wrong.

image


image

**Comment by 3link** [comment]
@robertrmartinez For the change to work with Prebid, it requires adjustments in Prebid beyond the LiveConnect version update. This draft in our fork shows how to do it: https://github.com/LiveIntent/Prebid.js/pull/20. A PR in the Prebid repository will follow soon.

**Comment by 3link** [comment]
@robertrmartinez This is the PR in Prebid: https://github.com/prebid/Prebid.js/pull/10425

**Comment by robertrmartinez** [comment]
Sorry! I got too excited.

Thanks for the quick update!

**Pull request merged**
